CFLAGS = -Wall
SRCS = sysdog.c
OUT = sysdog

CC = /mnt/NFS-RW/cross-compiler-tools/Raspberry/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc-4.7.2

all: $(OUT)
	$(CC) $(CFLAGS) $(SRCS) -o $(OUT)

